### PR TITLE
15 remove plots

### LINKED ISSUE #15: remove plot related functions
relates to https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/issues/2

Plots und prep functions are migrated to dedicated package

### PR DESCRIPTION
**Pull request by jacobvjk**
closes #15 

- deletes `prep_*()` and `plot_*()` functions
- updates dependencies in `R/imports.R`, `DESCRIPTION`, and `NAMESPACE`

### CODE REVIEW

**Comment by jacobvjk** [comment]
relates to https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/pull/11

**Comment by jacobvjk** [comment]
depends on https://github.com/RMI-PACTA/workflow.aggregate.loanbooks/pull/87

**Comment by jacobvjk** [comment]
also fyi @MonikaFu

**Comment by jacobvjk** [comment]
On R CMD notes:
```
❯ checking dependencies in R code ... NOTE
  Unexported objects imported by ':::' calls:
    'r2dii.plot:::abort_if_missing_names'
    'r2dii.plot:::abort_if_unknown_values'
    See the note in ?`:::` about the use of this operator.
```
addressed in #5 

addressed in #6

**Comment by jdhoffa** [comment]
I would say also depends on https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/pull/11 (not relates to)

**Review by jdhoffa — APPROVED** [review]
lgtm (pending https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/pull/11)

**Pull request merged**
